services:
  - type: web
    name: horizon-license-bot
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 8371496211:AAEb3etvEZ9MsfeGAwRnCD5htTWFoqrWKu4
      - key: ADMIN_CHAT_ID
        value: ""
